$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: convert_pipeline
description: Pipeline with 1 component.

compute: azureml:gpu-cluster
inputs: 
  target_backend: "onnx"
outputs:
  final_pipeline_output:
    type: mlflow_model
    mode: rw_mount

jobs:
  component_a:
    type: command
    component: file:./convert_component.yml
    inputs:
      conversion_component_input: 
        type: uri_folder
        path: ./mlruns/0/708024f552894a169962da22ee639ad9/artifacts/skl_model # randomForestClassifier trained on breast cancer
      conversion_target_input: ${{parent.inputs.target_backend}}

    outputs:
      component_a_output: 
        type: uri_folder
        mode: rw_mount
  component_b:
    type: command
    component: file:./optimize_component.yml
    inputs:
      optimization_component_model: 
        type: uri_folder
        path: ./mlruns/0/cf388f063ded42589539f0ae877b442f/artifacts/mnist_onnx # ONNX model trained on MNIST dataset
      optimization_shape_input: ${{parent.inputs.shape}} 
    outputs:
      component_b_output:
        type: uri_folder   
        mode: rw_mount 

